#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION=$1; shift
fi

local +x OUTPUT="$THIS_DIR/tmp/scratch-out/scratch.js"

case "$ACTION" in
  install)
    PREFIX="$THIS_DIR/tmp" npm install -g js-beautify
    ;;

  watch)
    reset
    cd "$THIS_DIR"
    mkdir -p tmp/scratch/
    mkdir -p tmp/scratch-out

    case "$(echo $@)" in
      "")
        touch tmp/scratch/scratch.jspp
        local +x CMD="my_js scratch compile $@"
        ${=CMD} || :
        process watch "-r tmp/scratch -r sh" "$CMD"
        ;;

      output)
        cd "$THIS_DIR"
        local +x CMD="my_js scratch pretty-output"
        ${=CMD} || :
        process watch "tmp/scratch-out" "my_js scratch pretty-output"
        ;;

      *)
        echo "!!! Invalid option: watch $@" >&2
        exit 5
        ;;
    esac
    ;;

  pretty-output)
    if ! which js-beautify &>/dev/null; then
      my_js scratch install
    fi

    local +x FILE="$THIS_DIR/tmp/scratch-out/scratch.js"
    if [[ -s "$FILE" ]]; then
      js-beautify "$FILE" --indent-size 2
      sh_color GREEN "\n=== {{DONE}} ==="
    fi
    ;;

  compile)
    cd "$THIS_DIR"/tmp/scratch
    js++ scratch.jspp -o "$OUTPUT"
    sh_color ORANGE "=== {{Running}}..."
    node "$OUTPUT"
    sh_color GREEN "=== {{DONE}} ==="
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

