#!/usr/bin/env zsh
#
# === {{CMD}} path/to/file.js # pretty prints a JavaScript file
#
set -u -e -o pipefail


if ! which js-beautify &>/dev/null; then
  my_js scratch install
fi

local +x FILE="$@"
js-beautify "$FILE" --indent-size 2
sh_color GREEN "\n=== {{DONE}} ===" >&2


